---
spring: 
    profiles:
        defult: production
        active: dev
---
debug: false
server:
    port: 8084
spring:
    activate: 
        on-profile: dev    
    application: 
        name: Insta Faces Search Service
    main:
        banner-mode: off
    jackson: 
        serialization:
            fail-on-empty-beans: false
    codec:
        max-in-memory-size: 20MB
    kafka:
        bootstrap-servers: 94.103.93.96:9092
        listener:
            type: batch          
        producer:
            group-id: instaGroup
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            auto-offset-reset: earliest            
            group-id: instaGroup                
logging:
    level:
        org.springframework.security: DEBUG                            
# deprecated custom  
# new custom
config:    
    security:
        profile:
            name: advanced
            webfilter:
                chain: development
        jwt:
            token:
                enabled: false
            name: standard
            secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
            expiration: 28800
    entity:
        core:
            enabled: false
    restfull:
        profile:
            name: insta-serv
    limit:
        followers: 10
        followings: 1
    dictionary:
        followers:
            ru: Авдотья, Аврора, Агата, Агафия, Агафья, Агнесса, Агния, Ада, Аделаида, Аделина, Аделия, Адель, Аида, Аксинья, Акулина, Алевтина, Алекса, Александра, Александрина, Алёна, Алеся, Алина, Алиса, Алла, Алсу, Альбина, Амалия, Амелия, Анастасия, Ангелина, Анжела, Анжелика, Анисья, Анна, Антонина, Анфиса, Аполлинария, Арина, Ася, Аэлита, Богдана, Божена, Бронислава, Валентина, Валерия, Ванда, Варвара, Василина, Василиса, Венера, Вера, Вероника, Вета, Викторина, Виктория, Вилена, Виола, Виолетта, Вита, Виталина, Виталия, Влада, Владана, Владислава, Галина, Гелла, Гертруда, ГлафираДарина, Дария, Дарья, Диана, Дина, Динара, Домника, Дора, Ева, Евангелина, Ева, Евгения, Евдокия, Екатерина, Алёна, Елена, Елизавета, Есения, Ефросинья, Жанна, Зинаида, Злата, Зоряна, Зоя, Иванна, Иветта, Изабелла, Изольда, Илга, Иллирика, Илона, Инга, Инесса, Инна, Иоанна, Ира, Ираида, Ирина, Искра, Ия, Калерия, Камилла, Капитолина, Карина, Каролина, Катерина, Кира, Клавдия, Клара, Кристина, Ксения, Лада, Лара, Лариса, Лера, Леся, Лидия, Лика, Лилия, Лина, Лия, Лолита, Луиза, Лукерья, Любовь, Людмила, Ляля, Магдалена, Магдалина, Майя, Макария, Маргарита, Марианна, Марина, Мария, Марта, Марфа, Марьяна, Мила, Милада, Милана, Милена, Милица, Мира, Мирослава, Мирра, Надежда, Наталия, Наталья, Нелли, Ника, Нина, Нинель, Нонна, Нора, Оксана, Октябрина, Олеся, Ольга, Павлина, Пелагея, Платонида, Полина, Прасковья, Рада, Радмила, Раиса, Раяна, Регина, Рената, Римма, Рита, Роза, Роксана, Россияна, Русалина, Руслана, Сабина, Светлана, Серафима, Снежана, Соня, София, Софья, Стелла, Стефания, Таисия, Тамара, Тамила, Татьяна, Таяна, Ульяна, Устинья, Август, Августин, Авраам, Агафон, Аким, Александр, Алексей, Альберт, Анастасий, Анатолий, Андрей, Анисий, Антон, Антоний, Анфим, Аполлинарий, Аполлон, Аристарх, Аркадий, Арсен, Арсений, Арсентий, Артем, Артём, Артемий, Артур, Архип, Бенедикт, Богдан, Болеслав, Борис, Борислав, Бронислав, Булат, Вадим, Валентин, Валерий, Василий, Вениамин, Викентий, Виктор, Вилен, Виссарион, Виталий, Влад, Владимир, Владислав, Владлен, Влас, Вольдемар, Всеволод, Вячеслав, Гавриил, Геннадий, Георгий, Герасим, Герман, Глеб, Гордей, Григорий, Давид, Давыд, Дамир, Даниил, Данил, Данила, Данислав, Демид, Демьян, Денис, Димитрий, Диомид, Дмитрий, Добрыня, Евгений, Евдоким, Евстахий, Егор, Егорий, Елисей, Емельян, Еремей, Ефим, Ефрем, Ждан, Захар, Зиновий, Зорийй, Иван, Игнат, Игнатий, Игорь, Иеремия, Иероним, Илларион, Илья, Иннокентий, Иосиф, Казимир, Касьян, Кир, Кирилл, Клим, Климент, Кондрат, Константин, Кузьма, Лев, Леонид, Леонтий, Лукьян, Макар, Макарий, Максим, Марат, Марк, Мартин, Мартын, Матвей, Мирон, Мирослав, Митрофан, Михаил, Модест, Моисей, Назар, Наум, Никанор, Никита, Никифор, Никодим, Никола, Николай, Никон, Олег, Осип, Остап, Павел, Парамон, Пётр, Платон, Потап, Прохор, Радий, Радзен, Радик, Радомир, Радослав, Ренат, Ринат, Родион, Роман, Ростислав, Руслан, Рустам, Савва, Савелий, Самсон, Святослав, Севастьян, Семён, Семён, Серафим, Сергей, Сидор, Спартак, Станислав, Степан, Тарас, Терентий, Тимофей, Тимур, Тихон, Трофим, Фаддей, Фёдор, Федот, Феликс, Филат, Филимон, Филипп, Флор, Фома, Харитон, Чарли, Эдуард, Эльдар, Эрик, Юлиан, Юлий, Юрий, Яков, Ян, Яромир, Ярослав
            en: Anatoly, Dmitry, Vasily, Alexandr, Alexander, Olga, Natali, Alexey, Sergey
        #blacklist: studio, forex, instrument, fuck, tourism, history, бижутерия, реклама, услуг, психология, территория, ресторан, строитель, педагог, питомник, стоматолог, ювелир, студия, корпорац, корпорат, фабрика, цветы, растения, типография, botox, botex, онлайн, online, маркет, юрист, школа, курсы, имидж, украшени, эпиляция, почта, лаборатор, лазер, компания, мастер, biznes, busines, limousin, prokat, dostavka, доставка, отделка, салон, обувь, белье, мебель, уборка, территория, заказ, работа, ссылк, $, корчма, #, |, \, /,coin, funny, _, подарк, extra, shop, пицца, дизайн, декор, •, блог, ремонт, Аксессуары, ЦЕНТР, Лофт, Медицинск, Компьютер, Двери, Грузоперевоз, Фотосалон, Подарки, Йога, БАННЕР, Авторск, Наращив, Интернет, СПА-центр, Агент, СЧАСТЛИВ, Страстн, Bitcoin, Магазин, Клининг, Маникюр, экскурс, семейн, фотограф, ТЕЛЕФОН, бизнес, нлп, терапия, реконструкц, худеем, худеть, парикмахер, косметика, косметолог, .by, .ru, .com, .org, club, заработок, ставки, betting
    db-rest-api:
        address: http://127.0.0.1:8080
        store-account: /api/createOrUpdateAccount
    proxy-provider:
        address: http://127.0.0.1:8000
