/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 24-авг-2021 16:55:34 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS rb_countries CASCADE
;

DROP TABLE IF EXISTS rb_currencies CASCADE
;

create sequence seq_rb_currencies
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

create sequence seq_rb_countries
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

/* Create Tables */

CREATE TABLE rb_countries
(
	country_id integer NOT NULL,
	country_iso varchar(10) NOT NULL,
	country_name varchar(100) NOT NULL
)
;

CREATE TABLE rb_currencies
(
	currency_iso varchar(3) NOT NULL,
	currency_id integer NOT NULL,
	currency_name varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE rb_countries ADD CONSTRAINT "PK_rb_countries"
	PRIMARY KEY (country_id)
;

ALTER TABLE rb_currencies ADD CONSTRAINT "PK_rb_currencies"
	PRIMARY KEY (currency_iso)
;
