#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
clear
cd ..
mvn spring-boot:run -Dexec.mainClass="org.dbs24.WaMonitoring" -Djava.awt.headless=true -Dspring-boot.run.arguments="--spring.main.banner-mode=off --debug=false --spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/wa_monitoring --springdoc.api-docs.enabled=false --springdoc.swagger-ui.enabled=false --spring.datasource.hikari.maximumPoolSize=20 --config.wa.contract.deprecated.update=300000 --config.wa.contract.futured.update=120000 --spring.datasource.username=wa_admin --spring.datasource.password=\$wa\$m4n0t1r9ng\$ "

