/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 12-авг-2021 14:17:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Расхождения UML и скрипта */
/* 1) timestamp with zone -> TIMESTAMP */
/* 2) sequences */
/* 3) removed empty index*/
/* 4) removed app_network empty status column*/

/* Create Sequences */

drop sequence IF EXISTS seq_prx_Proxies;

drop sequence IF EXISTS seq_prx_ProxyUsage;

drop sequence IF EXISTS seq_prx_Request;

drop sequence IF EXISTS seq_prx_Application;

drop sequence IF EXISTS seq_prx_Application_Network;

drop sequence IF EXISTS seq_prx_usage_error;

create sequence seq_prx_Proxies
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

create sequence seq_prx_ProxyUsage
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

create sequence seq_prx_Request
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

create sequence seq_prx_Application
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

create sequence seq_prx_Application_Network
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

create sequence seq_prx_usage_error
    increment 1
minvalue 1
maxvalue 9223372036854775807
start 1;

/* Drop Tables */

DROP TABLE IF EXISTS prx_alg_selection_ref CASCADE
;

DROP TABLE IF EXISTS prx_application_networks CASCADE
;

DROP TABLE IF EXISTS prx_application_status_ref CASCADE
;

DROP TABLE IF EXISTS prx_applications CASCADE
;

DROP TABLE IF EXISTS prx_countries_ref CASCADE
;

DROP TABLE IF EXISTS prx_error_types_ref CASCADE
;

DROP TABLE IF EXISTS prx_proxies CASCADE
;

DROP TABLE IF EXISTS prx_proxies_hist CASCADE
;

DROP TABLE IF EXISTS prx_proxy_providers CASCADE
;

DROP TABLE IF EXISTS prx_proxy_requests CASCADE
;

DROP TABLE IF EXISTS prx_proxy_statuses_ref CASCADE
;

DROP TABLE IF EXISTS prx_proxy_types_ref CASCADE
;

DROP TABLE IF EXISTS prx_proxy_usage_bans CASCADE
;

DROP TABLE IF EXISTS prx_proxy_usage_errors CASCADE
;

DROP TABLE IF EXISTS prx_proxy_usages CASCADE
;

DROP TABLE IF EXISTS prx_socks_auth_methods_ref CASCADE
;

/* Create Tables */

CREATE TABLE prx_alg_selection_ref
(
	alg_id integer NOT NULL,
	alg_name varchar(100) NOT NULL
)
;

CREATE TABLE prx_application_networks
(
	application_network_id integer NOT NULL,
	name varchar(50) NOT NULL
)
;

CREATE TABLE prx_application_status_ref
(
	application_status_id integer NOT NULL,
	application_status_name varchar(100) NOT NULL
)
;

CREATE TABLE prx_applications
(
	application_id integer NOT NULL,
	name varchar(50) NOT NULL,
	description varchar(256) NULL,
	application_network_id integer NOT NULL,
	application_status_id integer NOT NULL
)
;

CREATE TABLE prx_countries_ref
(
	country_id integer NOT NULL,
	country_iso varchar(10) NOT NULL,
	country_name varchar(100) NOT NULL
)
;

CREATE TABLE prx_error_types_ref
(
	error_type_id integer NOT NULL,
	name varchar(100) NOT NULL
)
;

CREATE TABLE prx_proxies
(
	proxy_id integer NOT NULL,
	actual_date TIMESTAMP NOT NULL,
	provider_id integer NOT NULL,
	url varchar(200) NOT NULL,
	socks_port integer NULL,
	http_port integer NULL,
	login varchar(100) NULL,
	pass varchar(100) NULL,
	url_ip_change varchar(200) NULL,
	country_id integer NULL,
	external_ip_address varchar(40) NULL,
	proxy_status_id integer NOT NULL,
	proxy_type_id integer NOT NULL,
	date_begin TIMESTAMP NOT NULL,
	date_end TIMESTAMP NULL,
	auth_method_id integer NULL,
	socks_client_data bytea NULL,
	traffic integer NULL
)
;

CREATE TABLE prx_proxies_hist
(
	proxy_id integer NOT NULL,
	actual_date TIMESTAMP NOT NULL,
	provider_id integer NULL,
	url varchar(200) NULL,
	socks_port integer NULL,
	http_port integer NULL,
	login varchar(100) NULL,
	pass varchar(100) NULL,
	url_ip_change varchar(200) NULL,
	country_id integer NULL,
	external_ip_address varchar(40) NULL,
	proxy_status_id integer NULL,
	proxy_type_id integer NULL,
	date_begin TIMESTAMP NULL,
	date_end TIMESTAMP NULL,
	auth_method_id integer NULL,
	socks_client_data bytea NULL,
	traffic integer NULL
)
;

CREATE TABLE prx_proxy_providers
(
	provider_id integer NOT NULL,
	provider_code varchar(20) NOT NULL,
	provider_name varchar(200) NOT NULL
)
;

CREATE TABLE prx_proxy_requests
(
	request_id integer NOT NULL,
	request_date TIMESTAMP NOT NULL,
	amount integer NOT NULL,
	proxy_type_id integer NULL,
	provider_id integer NULL,
	country_id integer NULL,
	application_id integer NOT NULL,
	alg_id integer NULL,
	session_start TIMESTAMP NULL,
	session_finish TIMESTAMP NULL
)
;

CREATE TABLE prx_proxy_statuses_ref
(
	proxy_status_id integer NOT NULL,
	proxy_status_name varchar(100) NOT NULL
)
;

CREATE TABLE prx_proxy_types_ref
(
	proxy_type_id integer NOT NULL,
	proxy_type_name varchar(100) NOT NULL
)
;

CREATE TABLE prx_proxy_usage_bans
(
	proxy_usage_error_id integer NOT NULL,
	application_network_id integer NOT NULL,
	proxy_id integer NOT NULL,
	banned_until_date TIMESTAMP NULL
)
;

CREATE TABLE prx_proxy_usage_errors
(
	error_id integer NOT NULL,
	usage_id integer NOT NULL,
	actual_date TIMESTAMP NOT NULL,
	error_type_id integer NOT NULL,
	log varchar(2000) NULL,
	application_id integer NOT NULL
)
;

CREATE TABLE prx_proxy_usages
(
	usage_id integer NOT NULL,
	request_id integer NOT NULL,
	proxy_id integer NOT NULL
)
;

CREATE TABLE prx_socks_auth_methods_ref
(
	socks_auth_method_id integer NOT NULL,
	socks_auth_method_name varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE prx_alg_selection_ref ADD CONSTRAINT "PK_prx_alg_selection_ref"
	PRIMARY KEY (alg_id)
;

ALTER TABLE prx_application_networks ADD CONSTRAINT "PK_prx_application_networks"
	PRIMARY KEY (application_network_id)
;

ALTER TABLE prx_application_status_ref ADD CONSTRAINT "PK_prx_application_status_ref"
	PRIMARY KEY (application_status_id)
;

ALTER TABLE prx_applications ADD CONSTRAINT "PK_prx_applications"
	PRIMARY KEY (application_id)
;

CREATE INDEX "IXFK_prx_applications_prx_application_networks" ON prx_applications (application_network_id ASC)
;

CREATE INDEX "IXFK_prx_applications_prx_application_status_ref" ON prx_applications (application_status_id ASC)
;

ALTER TABLE prx_countries_ref ADD CONSTRAINT "PK_prx_countries_ref"
	PRIMARY KEY (country_id)
;

ALTER TABLE prx_error_types_ref ADD CONSTRAINT "PK_prx_error_types_ref"
	PRIMARY KEY (error_type_id)
;

ALTER TABLE prx_proxies ADD CONSTRAINT "PK_prx_proxies"
	PRIMARY KEY (proxy_id)
;

CREATE INDEX "IXFK_prx_proxies_prx_countries_ref" ON prx_proxies (country_id ASC)
;

CREATE INDEX "IXFK_prx_proxies_prx_proxy_providers" ON prx_proxies (provider_id ASC)
;

CREATE INDEX "IXFK_prx_proxies_prx_proxy_statuses_ref" ON prx_proxies (proxy_status_id ASC)
;

CREATE INDEX "IXFK_prx_proxies_prx_proxy_types_ref" ON prx_proxies (proxy_type_id ASC)
;

CREATE INDEX "IXFK_prx_proxies_prx_socks_auth_methods_ref" ON prx_proxies (auth_method_id ASC)
;

ALTER TABLE prx_proxies_hist ADD CONSTRAINT "PK_prx_proxies_hist"
	PRIMARY KEY (actual_date,proxy_id)
;

CREATE INDEX "IXFK_prx_proxies_hist_prx_proxies" ON prx_proxies_hist (proxy_id ASC)
;

ALTER TABLE prx_proxy_providers ADD CONSTRAINT "PK_prx_proxy_providers"
	PRIMARY KEY (provider_id)
;

ALTER TABLE prx_proxy_requests ADD CONSTRAINT "PK_prx_proxy_request"
	PRIMARY KEY (request_id)
;

CREATE INDEX "IXFK_prx_proxy_request_prx_alg_selection_ref" ON prx_proxy_requests (alg_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_request_prx_applications" ON prx_proxy_requests (application_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_request_prx_countries_ref" ON prx_proxy_requests (country_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_request_prx_proxy_providers" ON prx_proxy_requests (provider_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_request_prx_proxy_types_ref" ON prx_proxy_requests (proxy_type_id ASC)
;

ALTER TABLE prx_proxy_statuses_ref ADD CONSTRAINT "PK_prx_proxy_statuses_ref"
	PRIMARY KEY (proxy_status_id)
;

ALTER TABLE prx_proxy_types_ref ADD CONSTRAINT "PK_prx_proxy_types_ref"
	PRIMARY KEY (proxy_type_id)
;

ALTER TABLE prx_proxy_usage_bans ADD CONSTRAINT "PK_prx_proxy_usage_bans"
	PRIMARY KEY (proxy_usage_error_id)
;

CREATE INDEX "IXFK_prx_proxy_usage_bans_prx_application_networks" ON prx_proxy_usage_bans (application_network_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_usage_bans_prx_proxies" ON prx_proxy_usage_bans (proxy_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_usage_bans_prx_proxy_usage_errors" ON prx_proxy_usage_bans (proxy_usage_error_id ASC)
;

ALTER TABLE prx_proxy_usage_errors ADD CONSTRAINT "PK_prx_proxy_usage_errors"
	PRIMARY KEY (error_id)
;

CREATE INDEX "IXFK_prx_proxy_usage_errors_prx_applications" ON prx_proxy_usage_errors (application_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_usage_errors_prx_error_types_ref" ON prx_proxy_usage_errors (error_type_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_usage_errors_prx_proxy_usage" ON prx_proxy_usage_errors (usage_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_usage_errors_prx_proxy_usage_bans" ON prx_proxy_usage_errors (error_id ASC)
;

ALTER TABLE prx_proxy_usages ADD CONSTRAINT "PK_prx_proxy_usage"
	PRIMARY KEY (usage_id)
;

CREATE INDEX "IXFK_prx_proxy_usage_prx_proxies" ON prx_proxy_usages (proxy_id ASC)
;

CREATE INDEX "IXFK_prx_proxy_usage_prx_proxy_request" ON prx_proxy_usages (request_id ASC)
;

ALTER TABLE prx_socks_auth_methods_ref ADD CONSTRAINT "PK_prx_socks_auth_methods_ref"
	PRIMARY KEY (socks_auth_method_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE prx_applications ADD CONSTRAINT "FK_prx_applications_prx_application_networks"
	FOREIGN KEY (application_network_id) REFERENCES prx_application_networks (application_network_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_applications ADD CONSTRAINT "FK_prx_applications_prx_application_status_ref"
	FOREIGN KEY (application_status_id) REFERENCES prx_application_status_ref (application_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxies ADD CONSTRAINT "FK_prx_proxies_prx_countries_ref"
	FOREIGN KEY (country_id) REFERENCES prx_countries_ref (country_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxies ADD CONSTRAINT "FK_prx_proxies_prx_proxy_providers"
	FOREIGN KEY (provider_id) REFERENCES prx_proxy_providers (provider_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxies ADD CONSTRAINT "FK_prx_proxies_prx_proxy_statuses_ref"
	FOREIGN KEY (proxy_status_id) REFERENCES prx_proxy_statuses_ref (proxy_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxies ADD CONSTRAINT "FK_prx_proxies_prx_proxy_types_ref"
	FOREIGN KEY (proxy_type_id) REFERENCES prx_proxy_types_ref (proxy_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxies ADD CONSTRAINT "FK_prx_proxies_prx_socks_auth_methods_ref"
	FOREIGN KEY (auth_method_id) REFERENCES prx_socks_auth_methods_ref (socks_auth_method_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxies_hist ADD CONSTRAINT "FK_prx_proxies_hist_prx_proxies"
	FOREIGN KEY (proxy_id) REFERENCES prx_proxies (proxy_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_requests ADD CONSTRAINT "FK_prx_proxy_request_prx_alg_selection_ref"
	FOREIGN KEY (alg_id) REFERENCES prx_alg_selection_ref (alg_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_requests ADD CONSTRAINT "FK_prx_proxy_request_prx_applications"
	FOREIGN KEY (application_id) REFERENCES prx_applications (application_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_requests ADD CONSTRAINT "FK_prx_proxy_request_prx_countries_ref"
	FOREIGN KEY (country_id) REFERENCES prx_countries_ref (country_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_requests ADD CONSTRAINT "FK_prx_proxy_request_prx_proxy_providers"
	FOREIGN KEY (provider_id) REFERENCES prx_proxy_providers (provider_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_requests ADD CONSTRAINT "FK_prx_proxy_request_prx_proxy_types_ref"
	FOREIGN KEY (proxy_type_id) REFERENCES prx_proxy_types_ref (proxy_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usage_bans ADD CONSTRAINT "FK_prx_proxy_usage_bans_prx_application_networks"
	FOREIGN KEY (application_network_id) REFERENCES prx_application_networks (application_network_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usage_bans ADD CONSTRAINT "FK_prx_proxy_usage_bans_prx_proxies"
	FOREIGN KEY (proxy_id) REFERENCES prx_proxies (proxy_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usage_bans ADD CONSTRAINT "FK_prx_proxy_usage_bans_prx_proxy_usage_errors"
	FOREIGN KEY (proxy_usage_error_id) REFERENCES prx_proxy_usage_errors (error_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usage_errors ADD CONSTRAINT "FK_prx_proxy_usage_errors_prx_applications"
	FOREIGN KEY (application_id) REFERENCES prx_applications (application_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usage_errors ADD CONSTRAINT "FK_prx_proxy_usage_errors_prx_error_types_ref"
	FOREIGN KEY (error_type_id) REFERENCES prx_error_types_ref (error_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usage_errors ADD CONSTRAINT "FK_prx_proxy_usage_errors_prx_proxy_usage"
	FOREIGN KEY (usage_id) REFERENCES prx_proxy_usages (usage_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usages ADD CONSTRAINT "FK_prx_proxy_usage_prx_proxies"
	FOREIGN KEY (proxy_id) REFERENCES prx_proxies (proxy_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE prx_proxy_usages ADD CONSTRAINT "FK_prx_proxy_usage_prx_proxy_request"
	FOREIGN KEY (request_id) REFERENCES prx_proxy_requests (request_id) ON DELETE Restrict ON UPDATE Restrict
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE prx_alg_selection_ref
	IS 'Список доступных алгоритмов по выбору прокси'
;

COMMENT ON TABLE prx_applications
	IS 'Список приложений, использующих прокси'
;

COMMENT ON TABLE prx_countries_ref
	IS 'Список стран расположения прокси'
;

COMMENT ON TABLE prx_error_types_ref
	IS 'Типы ошибок'
;

COMMENT ON TABLE prx_proxies
	IS 'Все возможные прокси'
;

COMMENT ON TABLE prx_proxies_hist
	IS 'Прокси картотека'
;

COMMENT ON TABLE prx_proxy_providers
	IS 'Провайдеры прокси'
;

COMMENT ON TABLE prx_proxy_requests
	IS 'Запросы на получение прокси'
;

COMMENT ON TABLE prx_proxy_statuses_ref
	IS 'Статусы прокси'
;

COMMENT ON TABLE prx_proxy_types_ref
	IS 'Типы прокси'
;

COMMENT ON TABLE prx_proxy_usage_errors
	IS 'Лог возникших во время использования прокси ошибок'
;

COMMENT ON TABLE prx_proxy_usages
	IS 'Лог использования прокси'
;
