---
spring:
    profiles:
        defult: production
        active: dev
---
debug: false
server:
    port: 8000
spring:
    activate:
        on-profile: dev
    application:
        name: Proxy Provider
    main:
        banner-mode: off
    jackson:
        serialization:
            fail-on-empty-beans: false
    datasource:
        url: jdbc:postgresql://193.178.170.145:5432/prx_assist_dev
        #url: jdbc:postgresql://127.0.0.1:5432/tik_assist_dev
        username: prx_admin
        password: $prx$m0n1t1c4re
        driver-class-name: org.postgresql.Driver
    jpa:
        #show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            cache:
                use_second_level_cache: true
        properties:
            hibernate:
                generate_statistics: false
                format_sql: true
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 1000
    codec:
        max-in-memory-size: 20MB
logging:
    level:
        org.springframework.security: DEBUG
# deprecated custom
# new custom
network:
    allowed-origins:
        additional: http://localhost:4200, https://localhost:4200
config:
    security:
        profile:
            name: advanced
            webfilter:
                chain: development
        jwt:
            token:
                enabled: false
            name: standard
            secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
            expiration: 28800
    entity:
        core:
            enabled: false
    persistence:
        name: proxy-core
        service:
            name: standard
    restfull:
        profile:
            name: proxy-core
#STATIC PROXY
    proxy:
        static:
            folder: proxy-core/import
            delete: false
            refresh: PT1H
            invalid-refresh: PT12H
    providers:
        astro:
            import:
                token: 1fb142e5c6b18088
                uri:
                    base: https://astroproxy.com
                    ports: /api/v1/ports
                    countries: /api/v1/countries
                refresh: 150000
        imm:
            import:
                refresh: 10000
                host: 178.20.45.178
                port: 1500
    algorithm-selection:
        min-used:
            days-to-search: 3
        longest-not-used:
            days-to-search: 3
# @ConfigurationProperties
refs:
    api:
        host: http://193.178.170.145:10000
        endpoint:
            countries: /api/getCountries
            hosts-to-countries: /api/getHostToCountryMap
    synchronize: true

springdoc:
    version: '@springdoc.version@'
    api-docs:
        enabled: true
    swagger-ui:
        use-root-path: true
        enabled: true
        # path: /swagger-ui-custom.html
        operationsSorter: method
    cache:
        disabled: true

