/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-авг-2021 11:51:08 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */
/* No order_execution_progress_table; no user OAuth2.0 fields*/
/* Drop Tables */

DROP TABLE IF EXISTS tik_action_types_ref CASCADE
;

DROP TABLE IF EXISTS tik_bot_registration_types_ref CASCADE
;

DROP TABLE IF EXISTS tik_bot_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_bots CASCADE
;

DROP TABLE IF EXISTS tik_bots_hist CASCADE
;

DROP TABLE IF EXISTS tik_countries_ref CASCADE
;

DROP TABLE IF EXISTS tik_currencies_ref CASCADE
;

DROP TABLE IF EXISTS tik_discount_to_accounts_quantity CASCADE
;

DROP TABLE IF EXISTS tik_order_action_result_ref CASCADE
;

DROP TABLE IF EXISTS tik_order_actions CASCADE
;

DROP TABLE IF EXISTS tik_order_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_payment_types_ref CASCADE
;

DROP TABLE IF EXISTS tik_phone_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_phone_usages CASCADE
;

DROP TABLE IF EXISTS tik_phones CASCADE
;

DROP TABLE IF EXISTS tik_plan_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_plan_template_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_plan_templates CASCADE
;

DROP TABLE IF EXISTS tik_plan_templates_hist CASCADE
;

DROP TABLE IF EXISTS tik_promocodes CASCADE
;

DROP TABLE IF EXISTS tik_sum_to_actions_quantity CASCADE
;

DROP TABLE IF EXISTS tik_tiktok_accounts CASCADE
;

DROP TABLE IF EXISTS tik_user_deposit_payments CASCADE
;

DROP TABLE IF EXISTS tik_user_deposits CASCADE
;

DROP TABLE IF EXISTS tik_user_deposits_hist CASCADE
;

DROP TABLE IF EXISTS tik_user_orders CASCADE
;

DROP TABLE IF EXISTS tik_user_orders_hist CASCADE
;

DROP TABLE IF EXISTS tik_user_plans CASCADE
;

DROP TABLE IF EXISTS tik_user_plans_hist CASCADE
;

DROP TABLE IF EXISTS tik_user_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_user_subscription_statuses_ref CASCADE
;

DROP TABLE IF EXISTS tik_user_subscriptions CASCADE
;

DROP TABLE IF EXISTS tik_user_subscriptions_hist CASCADE
;

DROP TABLE IF EXISTS tik_users CASCADE
;

DROP TABLE IF EXISTS tik_users_hist CASCADE
;


create sequence seq_tik_discount_to_accounts_quantity
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_user_deposits
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_usage_errors
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_phone_usages
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_phones
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_users
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_orders
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_order_action_errors
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_discount_to_subscriptions_quantity
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_plan_templates
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_deposit_payments
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_user_subscriptions
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_promocodes
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_user_plans
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_tiktok_accounts
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_bots
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;

create sequence seq_tik_order_actions
    increment 1
    minvalue 1
    maxvalue 9223372036854775807
    start 1;


/* Create Tables */

CREATE TABLE tik_action_types_ref
(
	action_type_id integer NOT NULL,
	action_type_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_bot_registration_types_ref
(
	bot_registration_type_id integer NOT NULL,
	bot_registration_type_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_bot_statuses_ref
(
	bot_status_id integer NOT NULL,
	bot_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_bots
(
	bot_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	bot_status_id integer NOT NULL,
	bot_registration_type_id integer NOT NULL,
	create_date timestamp without time zone NOT NULL,
	sec_user_id varchar(200) NULL,
	bot_note varchar(200) NULL,
	phone_number varchar(20) NULL,
	email varchar(100) NULL,
	pass varchar(50) NULL,
	attributes bytea NULL
)
;

CREATE TABLE tik_bots_hist
(
	bot_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	bot_status_id integer NULL,
	bot_registration_type_id integer NULL,
	create_date timestamp without time zone NULL,
	sec_user_id varchar(200) NULL,
	bot_note varchar(200) NULL,
	phone_number varchar(20) NULL,
	email varchar(100) NULL,
	pass varchar(50) NULL,
	attributes bytea NULL
)
;

CREATE TABLE tik_countries_ref
(
	country_id integer NOT NULL,
	country_iso varchar(10) NOT NULL,
	country_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_currencies_ref
(
	currency_iso varchar(3) NOT NULL,
	currency_id varchar(3) NOT NULL,
	currency_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_discount_to_accounts_quantity
(
	discount_id integer NOT NULL,
	plan_template_id integer NULL,
	up_to_accounts_quantity integer NOT NULL,
	discount integer NOT NULL
)
;

CREATE TABLE tik_order_action_result_ref
(
	order_action_result_id integer NOT NULL,
	order_action_result_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_order_actions
(
	order_action_id integer NOT NULL,
	order_id bigint NOT NULL,
	order_action_result_id integer NULL,
	start_date timestamp without time zone NOT NULL,
	finish_date timestamp without time zone NULL,
	bot_id integer NOT NULL,
	note varchar(200) NULL,
	error_message varchar(2000) NULL
)
;

CREATE TABLE tik_order_statuses_ref
(
	order_status_id integer NOT NULL,
	order_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_payment_types_ref
(
	payment_type_id integer NOT NULL,
	payment_type_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_phone_statuses_ref
(
	phone_status_id integer NOT NULL,
	phone_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_phone_usages
(
	phone_usage_id integer NOT NULL,
	phone_id integer NULL,
	actual_date timestamp without time zone NOT NULL,
	is_success boolean NOT NULL,
	error_message varchar(2000) NULL
)
;

CREATE TABLE tik_phones
(
	phone_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	phone_status_id integer NOT NULL,
	device_id varchar(100) NOT NULL,
	install_id varchar(100) NOT NULL,
	apk_attributes bytea NULL,
	apk_hash_id varchar(400) NULL
)
;

CREATE TABLE tik_plan_statuses_ref
(
	plan_status_id integer NOT NULL,
	plan_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_plan_template_statuses_ref
(
	plan_template_status_id integer NOT NULL,
	plan_template_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_plan_templates
(
	plan_template_id integer NOT NULL,
	plan_template_name varchar(100) NOT NULL,
	plan_template_sum numeric(22,4) NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	plan_template_status_id integer NOT NULL,
	views_amount integer NULL,
	likes_amount integer NULL,
	followers_amount integer NULL,
	comments_amount integer NULL,
	reposts_amount integer NULL
)
;

CREATE TABLE tik_plan_templates_hist
(
	plan_template_id integer NOT NULL,
	plan_template_name varchar(100) NULL,
	plan_template_sum numeric(22,4) NULL,
	actual_date timestamp without time zone NOT NULL,
	plan_template_status_id integer NULL,
	views_amount integer NULL,
	likes_amount integer NULL,
	followers_amount integer NULL,
	comments_amount integer NULL,
	reposts_amount integer NULL
)
;

CREATE TABLE tik_promocodes
(
	promocode_id integer NOT NULL,
	promocode_value varchar(50) NOT NULL,
	promocode_discount integer NOT NULL,
	is_active boolean NOT NULL,
	user_id integer NULL,
	begin_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone NOT NULL,
	actual_date timestamp without time zone NOT NULL
)
;

CREATE TABLE tik_sum_to_actions_quantity
(
	sum_id integer NOT NULL,
	action_type_id integer NOT NULL,
	up_to_action_quantity integer NOT NULL,
	sum numeric(22,4) NOT NULL
)
;

CREATE TABLE tik_tiktok_accounts
(
	account_id integer NOT NULL,
	sec_user_id varchar(200) NOT NULL,
	user_id integer NULL,
	username varchar(100) NULL
)
;

CREATE TABLE tik_user_deposit_payments
(
	payment_id integer NOT NULL,
	payment_sum numeric(22,4) NOT NULL,
	payment_type_id integer NULL,
	plan_id integer NULL,
	order_id integer NULL,
	user_id integer NOT NULL,
	user_subscription_id integer NULL,
	payment_date timestamp without time zone NULL
)
;

CREATE TABLE tik_user_deposits
(
	user_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	currency_iso varchar(3) NOT NULL,
	rest_sum numeric(22,4) NOT NULL
)
;

CREATE TABLE tik_user_deposits_hist
(
	user_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	currency_iso varchar(3) NULL,
	rest_sum numeric(22,4) NULL
)
;

CREATE TABLE tik_user_orders
(
	order_id integer NOT NULL,
	plan_id integer NULL,
	order_status_id integer NOT NULL,
	action_type_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	user_id integer NOT NULL,
	begin_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone NOT NULL,
	cancel_date timestamp without time zone NULL,
	actions_amount integer NOT NULL,
	currency_iso varchar(3) NULL,
	order_sum numeric(22,4) NULL,
	tiktok_uri varchar(200) NULL,
	aweme_id varchar(40) NULL,
	cid varchar(30) NULL,
	promocode_id integer NULL,
	account_id integer NULL
)
;

CREATE TABLE tik_user_orders_hist
(
	order_id integer NOT NULL,
	plan_id integer NULL,
	order_status_id integer NULL,
	order_type_id integer NULL,
	actual_date timestamp without time zone NOT NULL,
	user_id integer NULL,
	begin_date timestamp without time zone NULL,
	end_date timestamp without time zone NULL,
	cancel_date timestamp without time zone NULL,
	actions_amount integer NULL,
	currency_iso varchar(3) NULL,
	order_sum numeric(22,4) NULL,
	tiktok_uri varchar(200) NULL,
	aweme_id varchar(40) NULL,
	cid varchar(30) NULL,
	promocode_id integer NULL
)
;

CREATE TABLE tik_user_plans
(
	plan_id integer NOT NULL,
	user_id integer NOT NULL,
	account_id integer NULL,
	plan_template_id integer NULL,
	user_subscription_id integer NULL,
	plan_status_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	begin_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone NOT NULL,
	cancel_date timestamp without time zone NULL,
	currency_iso varchar(3) NULL,
	plan_sum numeric(22,4) NULL,
	promocode_id integer NULL,
	views_amount integer NULL,
	likes_amount integer NULL,
	followers_amount integer NULL,
	comments_amount integer NULL,
	reposts_amount integer NULL
)
;

CREATE TABLE tik_user_plans_hist
(
	plan_id integer NOT NULL,
	user_id integer NULL,
	account_id integer NULL,
	plan_template_id integer NULL,
	user_subscription_id integer NULL,
	plan_status_id integer NULL,
	actual_date timestamp without time zone NOT NULL,
	begin_date timestamp without time zone NULL,
	end_date timestamp without time zone NULL,
	cancel_date timestamp without time zone NULL,
	currency_iso varchar(3) NULL,
	plan_sum numeric(22,4) NULL,
	promocode_id integer NULL,
	views_amount integer NULL,
	likes_amount integer NULL,
	followers_amount integer NULL,
	comments_amount integer NULL,
	reposts_amount integer NULL
)
;

CREATE TABLE tik_user_statuses_ref
(
	user_status_id integer NOT NULL,
	user_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_user_subscription_statuses_ref
(
	user_subscription_status_id integer NOT NULL,
	user_subscription_status_name varchar(100) NOT NULL
)
;

CREATE TABLE tik_user_subscriptions
(
	user_subscription_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	begin_date timestamp without time zone NULL,
	end_date timestamp without time zone NULL,
	cancel_date timestamp without time zone NULL,
	promocode_id integer NULL,
	user_subscription_status_id integer NOT NULL,
	currency_iso varchar(3) NULL,
	subscription_sum numeric(22,4) NULL,
	user_id integer NOT NULL
)
;

CREATE TABLE tik_user_subscriptions_hist
(
	user_subscription_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	begin_date timestamp without time zone NULL,
	end_date timestamp without time zone NULL,
	cancel_date timestamp without time zone NULL,
	promocode_id integer NULL,
	user_subscription_status_id integer NULL,
	currency_iso varchar(3) NULL,
	subscription_sum numeric(22,4) NULL,
	user_id integer NULL
)
;

CREATE TABLE tik_users
(
	user_id integer NOT NULL,
	email varchar(200) NOT NULL,
	hash_pass varchar(200) NULL,
	user_name varchar(128) NULL,
	actual_date timestamp without time zone NOT NULL,
	country_id integer NOT NULL,
	user_phone_num varchar(50) NULL,
	user_status_id integer NOT NULL
)
;

CREATE TABLE tik_users_hist
(
	user_id integer NOT NULL,
	actual_date timestamp without time zone NOT NULL,
	email varchar(200) NULL,
	hash_pass varchar(200) NULL,
	user_name varchar(128) NULL,
	user_status_id integer NULL,
	user_phone_num varchar(50) NULL,
	country_id varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tik_action_types_ref ADD CONSTRAINT "PK_tik_order_types_ref"
	PRIMARY KEY (action_type_id)
;

ALTER TABLE tik_bot_registration_types_ref ADD CONSTRAINT "PK_tik_bot_registry_types_ref"
	PRIMARY KEY (bot_registration_type_id)
;

ALTER TABLE tik_bot_statuses_ref ADD CONSTRAINT "PK_tik_bot_statuses_ref"
	PRIMARY KEY (bot_status_id)
;

ALTER TABLE tik_bots ADD CONSTRAINT "PK_tik_bots"
	PRIMARY KEY (bot_id)
;

CREATE INDEX "IXFK_tik_bots_tik_bot_registry_types_ref" ON tik_bots (bot_registration_type_id ASC)
;

CREATE INDEX "IXFK_tik_bots_tik_bot_statuses_ref" ON tik_bots (bot_status_id ASC)
;

ALTER TABLE tik_bots_hist ADD CONSTRAINT "PK_tik_bots_hist"
	PRIMARY KEY (bot_id,actual_date)
;

CREATE INDEX "IXFK_tik_bots_hist_tik_bots" ON tik_bots_hist (bot_id ASC)
;

ALTER TABLE tik_countries_ref ADD CONSTRAINT "PK_tik_order_action_error_types_ref"
	PRIMARY KEY (country_id)
;

ALTER TABLE tik_currencies_ref ADD CONSTRAINT "PK_tik_currencies_ref"
	PRIMARY KEY (currency_iso)
;

ALTER TABLE tik_discount_to_accounts_quantity ADD CONSTRAINT "PK_tik_discount_to_subscriptions_quantity"
	PRIMARY KEY (discount_id)
;

ALTER TABLE tik_order_action_result_ref ADD CONSTRAINT "PK_tik_order_action_error_types_ref"
	PRIMARY KEY (order_action_result_id)
;

ALTER TABLE tik_order_actions ADD CONSTRAINT "PK_tik_order_actions"
	PRIMARY KEY (order_action_id)
;

CREATE INDEX "IXFK_tik_order_actions_tik_bots" ON tik_order_actions (bot_id ASC)
;

CREATE INDEX "IXFK_tik_order_actions_tik_order_action_result_ref" ON tik_order_actions (order_action_result_id ASC)
;

CREATE INDEX "IXFK_tik_order_actions_tik_user_orders" ON tik_order_actions (order_id ASC)
;

ALTER TABLE tik_order_statuses_ref ADD CONSTRAINT "PK_tik_order_statuses_ref"
	PRIMARY KEY (order_status_id)
;

ALTER TABLE tik_payment_types_ref ADD CONSTRAINT "PK_tik_payment_types_ref"
	PRIMARY KEY (payment_type_id)
;

ALTER TABLE tik_phone_statuses_ref ADD CONSTRAINT "PK_tik_phone_statuses_ref"
	PRIMARY KEY (phone_status_id)
;

ALTER TABLE tik_phone_usages ADD CONSTRAINT "PK_tik_phones_usage"
	PRIMARY KEY (phone_usage_id)
;


CREATE INDEX "IXFK_tik_phones_usage_tik_phones" ON tik_phone_usages (phone_id ASC)
;

ALTER TABLE tik_phones ADD CONSTRAINT "PK_tik_phones"
	PRIMARY KEY (phone_id)
;

CREATE INDEX "IXFK_tik_phones_tik_phone_statuses_ref" ON tik_phones (phone_status_id ASC)
;

ALTER TABLE tik_plan_statuses_ref ADD CONSTRAINT "PK_tik_subscription_statuses_ref"
	PRIMARY KEY (plan_status_id)
;

ALTER TABLE tik_plan_template_statuses_ref ADD CONSTRAINT "PK_tik_plan_template_statuses_ref"
	PRIMARY KEY (plan_template_status_id)
;

ALTER TABLE tik_plan_templates ADD CONSTRAINT "PK_tik_subscription_types_ref"
	PRIMARY KEY (plan_template_id)
;

CREATE INDEX "IXFK_tik_plan_templates_tik_plan_template_statuses_ref" ON tik_plan_templates (plan_template_status_id ASC)
;

ALTER TABLE tik_plan_templates_hist ADD CONSTRAINT "PK_tik_subscription_types_ref"
	PRIMARY KEY (plan_template_id,actual_date)
;

CREATE INDEX "IXFK_tik_plan_templates_hist_tik_plan_templates" ON tik_plan_templates_hist (plan_template_id ASC)
;

ALTER TABLE tik_promocodes ADD CONSTRAINT "PK_tik_promocodes"
	PRIMARY KEY (promocode_id)
;

ALTER TABLE tik_sum_to_actions_quantity ADD CONSTRAINT "PK_tik_sum_to_accounts_quantity"
	PRIMARY KEY (sum_id)
;

CREATE INDEX "IXFK_tik_sum_to_accounts_quantity_tik_action_types_ref" ON tik_sum_to_actions_quantity (action_type_id ASC)
;

ALTER TABLE tik_tiktok_accounts ADD CONSTRAINT "PK_tik_tiktok_account"
	PRIMARY KEY (account_id)
;

CREATE INDEX "IXFK_tik_tiktok_accounts_tik_users" ON tik_tiktok_accounts (user_id ASC)
;

ALTER TABLE tik_user_deposit_payments ADD CONSTRAINT "PK_tik_user_deposit_payments"
	PRIMARY KEY (payment_id)
;

CREATE INDEX "IXFK_tik_user_deposit_payments_tik_orders" ON tik_user_deposit_payments (order_id ASC)
;

CREATE INDEX "IXFK_tik_user_deposit_payments_tik_payment_types_ref" ON tik_user_deposit_payments (payment_type_id ASC)
;

CREATE INDEX "IXFK_tik_user_deposit_payments_tik_user_plans" ON tik_user_deposit_payments (plan_id ASC)
;

CREATE INDEX "IXFK_tik_user_deposit_payments_tik_user_subscriptions" ON tik_user_deposit_payments (user_subscription_id ASC)
;

CREATE INDEX "IXFK_tik_user_deposit_payments_tik_users" ON tik_user_deposit_payments (user_id ASC)
;

ALTER TABLE tik_user_deposits ADD CONSTRAINT "PK_tik_account_deposits"
	PRIMARY KEY (user_id,actual_date)
;

CREATE INDEX "IXFK_tik_account_deposits_tik_users" ON tik_user_deposits (user_id ASC)
;

ALTER TABLE tik_user_deposits_hist ADD CONSTRAINT "PK_tik_account_deposits"
	PRIMARY KEY (user_id,actual_date)
;

CREATE INDEX "IXFK_tik_account_deposits_tik_users" ON tik_user_deposits_hist (user_id ASC)
;

CREATE INDEX "IXFK_tik_user_deposits_hist_tik_user_deposits" ON tik_user_deposits_hist (user_id ASC,currency_iso ASC,actual_date ASC)
;

CREATE INDEX "IXFK_tik_user_deposits_hist_tik_user_deposits_02" ON tik_user_deposits_hist (user_id ASC,actual_date ASC)
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "PK_tik_user_orders"
	PRIMARY KEY (order_id)
;

CREATE INDEX "IXFK_tik_user_orders_tik_currencies_ref" ON tik_user_orders (currency_iso ASC)
;

CREATE INDEX "IXFK_tik_user_orders_tik_order_statuses_ref" ON tik_user_orders (order_status_id ASC)
;

CREATE INDEX "IXFK_tik_user_orders_tik_order_types_ref" ON tik_user_orders (action_type_id ASC)
;

CREATE INDEX "IXFK_tik_user_orders_tik_promocodes" ON tik_user_orders (promocode_id ASC)
;

CREATE INDEX "IXFK_tik_user_orders_tik_subscriptions" ON tik_user_orders (plan_id ASC)
;

CREATE INDEX "IXFK_tik_user_orders_tik_tiktok_accounts" ON tik_user_orders (account_id ASC)
;

CREATE INDEX "IXFK_tik_user_orders_tik_users" ON tik_user_orders (user_id ASC)
;

ALTER TABLE tik_user_orders_hist ADD CONSTRAINT "PK_tik_user_orders"
	PRIMARY KEY (order_id,actual_date)
;

CREATE INDEX "IXFK_tik_user_orders_hist_tik_user_orders" ON tik_user_orders_hist (order_id ASC)
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "PK_tik_subscriptions"
	PRIMARY KEY (plan_id)
;

CREATE INDEX "IXFK_tik_subscriptions_tik_promocodes" ON tik_user_plans (promocode_id ASC)
;

CREATE INDEX "IXFK_tik_subscriptions_tik_subscription_statuses_ref" ON tik_user_plans (plan_status_id ASC)
;

CREATE INDEX "IXFK_tik_subscriptions_tik_users" ON tik_user_plans (user_id ASC)
;

CREATE INDEX "IXFK_tik_user_plans_tik_currencies_ref" ON tik_user_plans (currency_iso ASC)
;

CREATE INDEX "IXFK_tik_user_plans_tik_plan_templates" ON tik_user_plans (plan_template_id ASC)
;

CREATE INDEX "IXFK_tik_user_plans_tik_tiktok_account" ON tik_user_plans (account_id ASC)
;

CREATE INDEX "IXFK_tik_user_plans_tik_user_subscriptions" ON tik_user_plans (user_subscription_id ASC)
;

ALTER TABLE tik_user_plans_hist ADD CONSTRAINT "PK_tik_user_plans_hist"
	PRIMARY KEY (plan_id,actual_date)
;

CREATE INDEX "IXFK_tik_user_plans_hist_tik_user_plans" ON tik_user_plans_hist (plan_id ASC)
;

ALTER TABLE tik_user_statuses_ref ADD CONSTRAINT "PK_tik_order_action_error_types_ref"
	PRIMARY KEY (user_status_id)
;

ALTER TABLE tik_user_subscription_statuses_ref ADD CONSTRAINT "PK_tik_user_subscription_statuses_ref"
	PRIMARY KEY (user_subscription_status_id)
;

ALTER TABLE tik_user_subscriptions ADD CONSTRAINT "PK_tik_user_subscriptions"
	PRIMARY KEY (user_subscription_id)
;

CREATE INDEX "IXFK_tik_user_subscriptions_tik_currencies_ref" ON tik_user_subscriptions (currency_iso ASC)
;

CREATE INDEX "IXFK_tik_user_subscriptions_tik_promocodes" ON tik_user_subscriptions (promocode_id ASC)
;

CREATE INDEX "IXFK_tik_user_subscriptions_tik_user_subscription_statuses_ref" ON tik_user_subscriptions (user_subscription_status_id ASC)
;

CREATE INDEX "IXFK_tik_user_subscriptions_tik_users" ON tik_user_subscriptions (user_id ASC)
;

ALTER TABLE tik_user_subscriptions_hist ADD CONSTRAINT "PK_tik_user_subscriptions_hist"
	PRIMARY KEY (user_subscription_id,actual_date)
;

CREATE INDEX "IXFK_tik_user_subscriptions_hist_tik_user_subscriptions" ON tik_user_subscriptions_hist (user_subscription_id ASC)
;

ALTER TABLE tik_users ADD CONSTRAINT "PK_tik_users"
	PRIMARY KEY (user_id)
;

CREATE INDEX "IXFK_tik_users_tik_countries_ref" ON tik_users (country_id ASC)
;

CREATE INDEX "IXFK_tik_users_tik_user_statuses_ref" ON tik_users (user_status_id ASC)
;

ALTER TABLE tik_users_hist ADD CONSTRAINT "PK_tik_users"
	PRIMARY KEY (user_id,actual_date)
;

CREATE INDEX "IXFK_tik_users_hist_tik_users" ON tik_users_hist (user_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE tik_bots ADD CONSTRAINT "FK_tik_bots_tik_bot_registry_types_ref"
	FOREIGN KEY (bot_registration_type_id) REFERENCES tik_bot_registration_types_ref (bot_registration_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_bots ADD CONSTRAINT "FK_tik_bots_tik_bot_statuses_ref"
	FOREIGN KEY (bot_status_id) REFERENCES tik_bot_statuses_ref (bot_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_bots_hist ADD CONSTRAINT "FK_tik_bots_hist_tik_bots"
	FOREIGN KEY (bot_id) REFERENCES tik_bots (bot_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_order_actions ADD CONSTRAINT "FK_tik_order_actions_tik_bots"
	FOREIGN KEY (bot_id) REFERENCES tik_bots (bot_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_order_actions ADD CONSTRAINT "FK_tik_order_actions_tik_order_action_result_ref"
	FOREIGN KEY (order_action_result_id) REFERENCES tik_order_action_result_ref (order_action_result_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_order_actions ADD CONSTRAINT "FK_tik_order_actions_tik_user_orders"
	FOREIGN KEY (order_id) REFERENCES tik_user_orders (order_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_phone_usages ADD CONSTRAINT "FK_tik_phones_usage_tik_phones"
	FOREIGN KEY (phone_id) REFERENCES tik_phones (phone_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_phones ADD CONSTRAINT "FK_tik_phones_tik_phone_statuses_ref"
	FOREIGN KEY (phone_status_id) REFERENCES tik_phone_statuses_ref (phone_status_id) ON DELETE Set Default
;

ALTER TABLE tik_plan_templates ADD CONSTRAINT "FK_tik_plan_templates_tik_plan_template_statuses_ref"
	FOREIGN KEY (plan_template_status_id) REFERENCES tik_plan_template_statuses_ref (plan_template_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_plan_templates_hist ADD CONSTRAINT "FK_tik_plan_templates_hist_tik_plan_templates"
	FOREIGN KEY (plan_template_id) REFERENCES tik_plan_templates (plan_template_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_sum_to_actions_quantity ADD CONSTRAINT "FK_tik_sum_to_accounts_quantity_tik_action_types_ref"
	FOREIGN KEY (action_type_id) REFERENCES tik_action_types_ref (action_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_tiktok_accounts ADD CONSTRAINT "FK_tik_tiktok_accounts_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposit_payments ADD CONSTRAINT "FK_tik_user_deposit_payments_tik_orders"
	FOREIGN KEY (order_id) REFERENCES tik_user_orders (order_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposit_payments ADD CONSTRAINT "FK_tik_user_deposit_payments_tik_payment_types_ref"
	FOREIGN KEY (payment_type_id) REFERENCES tik_payment_types_ref (payment_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposit_payments ADD CONSTRAINT "FK_tik_user_deposit_payments_tik_user_plans"
	FOREIGN KEY (plan_id) REFERENCES tik_user_plans (plan_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposit_payments ADD CONSTRAINT "FK_tik_user_deposit_payments_tik_user_subscriptions"
	FOREIGN KEY (user_subscription_id) REFERENCES tik_user_subscriptions (user_subscription_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposit_payments ADD CONSTRAINT "FK_tik_user_deposit_payments_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposits ADD CONSTRAINT "FK_tik_account_deposits_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_deposits_hist ADD CONSTRAINT "FK_tik_user_deposits_hist_tik_user_deposits_02"
	FOREIGN KEY (user_id,actual_date) REFERENCES tik_user_deposits (user_id,actual_date) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_currencies_ref"
	FOREIGN KEY (currency_iso) REFERENCES tik_currencies_ref (currency_iso) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_order_statuses_ref"
	FOREIGN KEY (order_status_id) REFERENCES tik_order_statuses_ref (order_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_order_types_ref"
	FOREIGN KEY (action_type_id) REFERENCES tik_action_types_ref (action_type_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_promocodes"
	FOREIGN KEY (promocode_id) REFERENCES tik_promocodes (promocode_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_subscriptions"
	FOREIGN KEY (plan_id) REFERENCES tik_user_plans (plan_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_tiktok_accounts"
	FOREIGN KEY (account_id) REFERENCES tik_tiktok_accounts (account_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders ADD CONSTRAINT "FK_tik_user_orders_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_orders_hist ADD CONSTRAINT "FK_tik_user_orders_hist_tik_user_orders"
	FOREIGN KEY (order_id) REFERENCES tik_user_orders (order_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_subscriptions_tik_promocodes"
	FOREIGN KEY (promocode_id) REFERENCES tik_promocodes (promocode_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_subscriptions_tik_subscription_statuses_ref"
	FOREIGN KEY (plan_status_id) REFERENCES tik_plan_statuses_ref (plan_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_subscriptions_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_user_plans_tik_currencies_ref"
	FOREIGN KEY (currency_iso) REFERENCES tik_currencies_ref (currency_iso) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_user_plans_tik_plan_templates"
	FOREIGN KEY (plan_template_id) REFERENCES tik_plan_templates (plan_template_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_user_plans_tik_tiktok_account"
	FOREIGN KEY (account_id) REFERENCES tik_tiktok_accounts (account_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans ADD CONSTRAINT "FK_tik_user_plans_tik_user_subscriptions"
	FOREIGN KEY (user_subscription_id) REFERENCES tik_user_subscriptions (user_subscription_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_plans_hist ADD CONSTRAINT "FK_tik_user_plans_hist_tik_user_plans"
	FOREIGN KEY (plan_id) REFERENCES tik_user_plans (plan_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_subscriptions ADD CONSTRAINT "FK_tik_user_subscriptions_tik_currencies_ref"
	FOREIGN KEY (currency_iso) REFERENCES tik_currencies_ref (currency_iso) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_subscriptions ADD CONSTRAINT "FK_tik_user_subscriptions_tik_promocodes"
	FOREIGN KEY (promocode_id) REFERENCES tik_promocodes (promocode_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_subscriptions ADD CONSTRAINT "FK_tik_user_subscriptions_tik_user_subscription_statuses_ref"
	FOREIGN KEY (user_subscription_status_id) REFERENCES tik_user_subscription_statuses_ref (user_subscription_status_id) ON DELETE Restrict
;

ALTER TABLE tik_user_subscriptions ADD CONSTRAINT "FK_tik_user_subscriptions_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_user_subscriptions_hist ADD CONSTRAINT "FK_tik_user_subscriptions_hist_tik_user_subscriptions"
	FOREIGN KEY (user_subscription_id) REFERENCES tik_user_subscriptions (user_subscription_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_users ADD CONSTRAINT "FK_tik_users_tik_countries_ref"
	FOREIGN KEY (country_id) REFERENCES tik_countries_ref (country_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_users ADD CONSTRAINT "FK_tik_users_tik_user_statuses_ref"
	FOREIGN KEY (user_status_id) REFERENCES tik_user_statuses_ref (user_status_id) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE tik_users_hist ADD CONSTRAINT "FK_tik_users_hist_tik_users"
	FOREIGN KEY (user_id) REFERENCES tik_users (user_id) ON DELETE Restrict ON UPDATE Restrict
;
