---
spring:
  profiles:
    defult: production
    active: dev
---
debug: false
server:
  port: 7083
spring:
  datasource:
    url: jdbc:oracle:thin:@//109.234.37.16:1521/ORCLPDB1
    username: gmail_manager
    password: 2N8rwGa2TNT0qY4C
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle8iDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      cache:
        use_second_level_cache: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
  activate:
    on-profile: dev
  application:
    name: Google Connection API
  main:
    banner-mode: off
  jackson:
    serialization:
      fail-on-empty-beans: false
  codec:
    max-in-memory-size: 20MB
  kafka:
    bootstrap-servers: 94.103.93.96:9092
    listener:
      type: batch
    producer:
      group-id: application-promo
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: application-promo
logging:
  level:
    org.springframework.security: DEBUG
# deprecated custom  
# new custom
config:
  persistence:
    name: g-connect
  security:
    profile:
      webfilter:
        chain: development
    jwt:
      token:
        enabled: false
      name: standard
      secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      expiration: 28800
  entity:
    core:
      enabled: false
  restfull:
    profile:
      name: g-connect
  storage:
    reboot: 1000

proxy:
  core:
    uri: http://193.178.170.145:8000
    api:
      book: /api/book
      unbook: /api/finalizeUsagesByApplicationId
      applications: /api/getApplications
    application-name: GoogleTasker
    required-use-time: 10000