#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
clear
cd ..
mvn spring-boot:run -Dexec.mainClass="org.dbs24.ad.server.AdServer" -Djava.awt.headless=true -Dspring-boot.run.arguments="--spring.main.banner-mode=off --debug=false --spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/tkn_cards_stage --spring.datasource.username=tkn_admin --spring.datasource.password=\$auth\$m2n7t1r59key\$ --config.restfull.security.wa-monitoring.return-detailed-errors=true "