---
spring:
    profiles:
        defult: production
        active: dev
---
debug: false
server:
    port: 8090
    error:
        include-message: always
spring:
    security:
        user:
            name: 1234
            password: 1234
    #    thymeleaf:
#        check-template: true
#        check-template-location: true
#        enabled: true
#        prefix: classpath:/templates/
#        suffix: .html
    activate:
        on-profile: dev
    application:
        name: Email spammer
    main:
        banner-mode: off
    jackson:
        serialization:
            fail-on-empty-beans: false
    datasource:
        url: jdbc:postgresql://193.178.170.145:5432/mailing_letters_dev
        #url: jdbc:postgresql://127.0.0.1:5432/tik_assist_dev
        username: ml_admin
        password: $ml9m0$pwd76
        driver-class-name: org.postgresql.Driver
    jpa:
        #show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            cache:
                use_second_level_cache: true
        properties:
            hibernate:
                #                generate_statistics: true
                format_sql: true
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 1000
    codec:
        max-in-memory-size: 20MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: brettcassin5@gmail.com
        password: YivljWDZVaS5Io
        protocol: smtp
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com

logging:
    level:
        org.springframework.security: DEBUG
# deprecated custom
# new custom
network:
    allowed-origins:
        additional: http://localhost:4200, https://localhost:4200, http://localhost:3000, https://localhost:3000
config:
    auth:
        auth-server-uri: http://localhost:8030
        oauth2:
            google-api: /api/tik/getTikUserJwtByGoogle
            facebook-api: /api/tik/getTikUserJwtByFacebook
    security:
        profile:
            name: advanced
            webfilter:
                chain: development
        jwt:
            token:
                enabled: false
            name: standard
            secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
            expiration: 28800
        staff-secret:
            ZetaSolPass
        redirect:
            url: https://tiktokfans-next-omega.vercel.app
            activation:
                api: /activate
                key:
                    length: 16
            password-change:
                api: /change_password
                key:
                    lifetime-hours: 24
    entity:
        core:
            enabled: false
    persistence:
        name: email-spammer
        service:
            name: standard
    restfull:
        profile:
            name: email-spammer
    refresh:
        10000