#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-16"
export MAVEN_OPTS="-Xms128m -XX:MaxDirectMemorySize=512M"

clear
/usr/lib/jvm/jdk-16/bin/java --version
/usr/lib/jvm/jdk-16/bin/java -jar target/services-monitoring.jar spring.config.name=application-dev  --spring.config.location=/home/kdg/dbs24/services-monitoring/src/main/resources/
