
debug: false
server:
    port: 10000
spring:
    activate:
        on-profile: dev
    application:
        name: Reference Book
    main:
        banner-mode: off
    jackson:
        serialization:
            fail-on-empty-beans: false
    datasource:
        url: jdbc:postgresql://193.178.170.145:5432/ref_book_dev
        username: ref_book_admin
        password: $rba$m0n1t0ringpwd
        driver-class-name: org.postgresql.Driver
    jpa:
        #show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            cache:
                use_second_level_cache: true
        properties:
            hibernate:
                generate_statistics: true
                format_sql: true
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 1000
    codec:
        max-in-memory-size: 20MB
logging:
    level:
        org.springframework.security: DEBUG

config:
    security:
        profile:
            name: advanced
            webfilter:
                chain: development
    entity:
        core:
            enabled: false
    persistence:
        name: ref-book
        service:
            name: standard
    restfull:
        profile:
            name: ref-book

springdoc:
    version: '@springdoc.version@'
    api-docs:
        enabled: true
    swagger-ui:
        use-root-path: true
        enabled: true
        # path: /swagger-ui-custom.html
        operationsSorter: method
    cache:
        disabled: true

