#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
clear
cd ..
mvn spring-boot:run -Dexec.mainClass="org.dbs24.app.notifier.NotifierServer" -Djava.awt.headless=true -Dspring-boot.run.arguments="--spring.main.banner-mode=off --debug=false --spring.datasource.url=jdbc:postgresql://193.178.170.145:5432/app_notifier_dev --spring.datasource.username=note_admin --spring.datasource.password=\$pr1m0\$Swd76 "
