---
spring: 
    profiles:
        defult: production
        active: dev
---
debug: false
server:
    port: 8044
#    security:
#        oauth2:
#            client:
#                registration:
#                    github:
#                        clientId: github-client-id
#                        clientSecret: github-client-secret   
#                access-token-uri: http://localhost:9999/oauth/token
#                user-authorization-uri: http://localhost:9999/oauth/authorize
#            resource:
#                token-info-uri: http://localhost:9999/oauth/check_token 
spring:
    activate: 
        on-profile: dev    
    application: 
        name: authoriation service
    main:
        banner-mode: off
    jackson: 
        serialization:
            fail-on-empty-beans: false
    datasource:
#        url: jdbc:oracle:thin:@//109.234.37.16/ORCLPDB1
#        username: wa_tracker
#        password: fGqybJ2LJKKvxd2N47P6
        url: jdbc:oracle:thin:@//52.209.167.145/ORCLPDB1
        username: readonly
        password: OD6TevvIjSHn        

        driver-class-name: oracle.jdbc.OracleDriver
#        driver-class-name: org.postgresql.Driver
        hikari:
            minimumIdle: 5
            maximumPoolSize: 20
            idleTimeout: 30000
            maxLifetime: 2000000
            connectionTimeout: 30000
            poolName: HikariPoolBooks        
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.Oracle12cDialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            cache:
                use_second_level_cache: true
        properties:
            hibernate:
                #generate_statistics: true
                default_schema: wa_tracker
                format_sql: true
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 500
    rsocket:
        server: 
            port: 7013
            transport: tcp
            mapping-path: /rsocket    
#    spring:
#        cache:
#            cache-names: itemCache
#            type: ehcache
#            ehcache:
#                config: classpath:ehcache.xml            
logging:
    level:
        org.springframework.security: DEBUG                            
# deprecated custom  
# new custom
config:
    wa:
        online-test:   
            enabled: true
            #url: http://127.0.0.1:8040
            url: http://193.178.170.145:8040
            create-activity-path: api/createActivities
            get-activity-path: api/getActivities
            update: 1000
            subscription:
                update: 5000
    security:
        profile:
            name: advanced
            webfilter:
                chain: development
        jwt:
            name: standard
            secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
            expiration: 28800
    entity:
        core:
            enabled: false
    persistence:
        name: wa-migration
        service:
            name: standard
    restfull:
        profile:
            name: wa-migration
#        security:
#            profile:
#                name: reactive
    monitoring:
        enabled: false
        port: 7007
        #address: 130.211.198.183        
        address: 127.0.0.1
# @ConfigurationProperties
test:
    phonesList:
        8NKTR6D6Q2IB0ULXCWPK8R792Y3E5R: 4917666852000
        MCUT9TFBEV3CG1JHTSHAQCEAVGA435: 12428053064
#        EFIEHIJLTNAWPY4XIVAMQSQLR4B5FG: 919652740995
        LMS11I9FS3E90RU47B0LZ3ZVHMHUVY: 4915127551418        
