#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
clear
cd ..
mvn spring-boot:run -Dexec.mainClass="org.dbs24.card.pmt.CardPaymentApplication" -Djava.awt.headless=true -Dspring-boot.run.arguments="--spring.main.banner-mode=off --debug=false --spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pmt_card_dev --spring.datasource.username=pmt_admin --spring.datasource.password=\$pmt\$m52c47t1r519key\$"
