---
spring:
  profiles:
    defult: production
    active: dev
---
debug: false
server:
  port: 7070
  error:
    include-message: always
spring:
  #    thymeleaf:
  #        check-template: true
  #        check-template-location: true
  #        enabled: true
  #        prefix: classpath:/templates/
  #        suffix: .html
  activate:
    on-profile: dev
  application:
    name: TikTok assistant
  main:
    banner-mode: off
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    #show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      cache:
        use_second_level_cache: true
    properties:
      hibernate:
        #                generate_statistics: true
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
  codec:
    max-in-memory-size: 20MB
logging:
  level:
    org.springframework.security: DEBUG
# deprecated custom
# new custom
network:
  allowed-origins:
    additional: http://localhost:4200, https://localhost:4200, http://localhost:3000, https://localhost:3000
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
  swagger-ui:
    use-root-path: true
    enabled: true
    operationsSorter: method
  cache:
    disabled: true
config:
  security:
    profile:
      name: advanced
      webfilter:
        chain: development
  entity:
    core:
      enabled: false
  persistence:
    name: tik-dev-api
    service:
      name: standard
  restfull:
    profile:
      name: tik-dev-api
