---
spring: 
    profiles:
        defult: production
        active: dev
---
debug: false
server:
    port: 7080
spring:
    activate: 
        on-profile: dev    
    application: 
        name: App Promo
    main:
        banner-mode: off
    jackson: 
        serialization:
            fail-on-empty-beans: false
    datasource:
        url: jdbc:postgresql://193.178.170.145:5432/app_promo_dev
        username: promo_admin
        password: $pr0m78$pwd76
        driver-class-name: org.postgresql.Driver     
    jpa:
        #show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            cache:
                use_second_level_cache: true
        properties:
            hibernate:
#                generate_statistics: true
                format_sql: true
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 20
    codec:
        max-in-memory-size: 20MB
    kafka:
        listener:
            type: batch
        bootstrap-servers: 94.103.93.96:9092
        producer:
            group-id: application-promo
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
    level:
        org.springframework.security: DEBUG                            
# deprecated custom  
# new custom
network:
    allowed-origins:
        additional: http://localhost:4200, https://localhost:4200
springdoc:
    version: '@springdoc.version@'
    api-docs:
        enabled: true
    swagger-ui:
        use-root-path: true
        enabled: true
        #path: /swagger-ui-custom.html
        operationsSorter: method       
    cache:
        disabled: true             
config:
    application:
        auto-reboot:
            enable: true
            cmd: systemctl restart app-promo
            #daily: 18000
            #frequency: 7200
            #freeMemoryLimit: 140000000
            #attempts: 3
            liveness:
                #uri: http://127.0.0.1:7080
                #path: /api/liveness
    orders:
        processing:
            tasks-per-action: 3
    security:
        profile:
            name: advanced
            webfilter:
                chain: development
        jwt:
            token:
                enabled: false
            name: standard
            secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
            expiration: 28800
    entity:
        core:
            enabled: false
    persistence:
        name: app-promo
        service:
            name: standard
    restfull:
        profile:
            name: app-promo
#        security:
#            profile:
#                name: reactive
# @ConfigurationProperties
refs:
    synchronize: true

# Proxy-core properties
proxy:
    core:
        uri: http://193.178.170.145:8000
        api:
            book: /api/book
            book-by-id: /api/bookById
            unbook: /api/finalizeUsagesByApplicationId
            applications: /api/getApplications
        application-name: GoogleTasker
        required-use-time: 10000