#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
clear
cd ..
mvn spring-boot:run -Dexec.mainClass="org.dbs24.cloud.server.RegistryServer" -Djava.awt.headless=true -Dspring-boot.run.arguments="--spring.main.banner-mode=off --debug=false "