#!/bin/sh
clear
export JAVA_HOME="/usr/lib/jvm/jdk-16"
export MAVEN_OPTS="-Xms1024m"
cd ..
mvn -version
mvn clean install validate -DskipTests=true
cd retail-loan-contracts
mvn exec:java -Dexec.mainClass="org.dbs24.RetailLoanContractBoot"