#!/bin/sh
clear
export JAVA_HOME="/usr/lib/jvm/jdk-16"
export MAVEN_OPTS="-Xms1024m"
cd ..
rm -rf ../.m2/repository/org/dbs24
mvn -version
mvn clean install -Pprofile_dev
cd retail-loan-contracts
mvn clean install -Pprofile_dev
mvn test -Pprofile_test_dev -Dtest=org.dbs24.test.TestRSocket -DforkMode=once surefire:test