#!/bin/sh
clear
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
export MAVEN_OPTS="-Xms1024m"
cd ..
rm -rf ../.m2/repository/org/dbs24
mvn -version
mvn clean install -Pjava8_dev
cd retail-loan-contracts
mvn clean install -Pjava8_dev
mvn test -Pjava8_test_dev -Dtest=org.dbs24.test.TestRSocket -DforkMode=once surefire:test