#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-16" 
export MAVEN_OPTS="-Xms1024m"
cd ..
mvn clean install -DskipTests=true
cd retail-loan-contracts
mvn exec:java -Dexec.mainClass="org.dbs24.RetailLoanContractBoot"
#mvn exec:java -Dexec.mainClass="org.dbs24.RetailLoanContractBoot" -Dexec.classpathScope=runtime