#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/jdk-16" 
export MAVEN_OPTS="-Xms1024m"
clear
mvn -version
#cd ..

#java -jar target/retail-loan-contracts-jar-with-dependencies.jar --spring.config.location=classpath:/target/application.properties

#java -jar ../libs/retail-loan-contracts.jar 
mvn exec:java ../libs/retail-loan-contracts.jar

