#!/bin/sh
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
export MAVEN_OPTS="-Xms1024m"
mvn clean install -DskipTests=true
mvn exec:java -Dexec.mainClass="org.dbs24.RetailLoanContractBoot"
#mvn exec:java -Dexec.mainClass="org.dbs24.RetailLoanContractBoot" -Dexec.classpathScope=runtime

